### ISSUE TITLE
使用上的问题

### ISSUE THREAD

**Issue by elcarim5efil** [regular-ui/rgui-tools#1]
请问rgui-tools的主要用途是对js、css模块进行打包吗？请问我应当如何开始使用这个工具呢？您能够给我一些建议吗？

**Comment by rainfore** [comment]
rgui-tools主要帮助regular-ui的组件开发者进行开发用的，比如每个仓库中组件的打包、测试和发布等等。
上次我讲的那个功能只是把打包功能借过来在项目中用用，目前这个工具功能还是比较弱。
你有什么需求可以给我提，我看能不能实现。

**Comment by elcarim5efil** [comment]
原来是针对regular-ui的组件进行打包，因为在课程上看到您用的这个工具在开发调试过程都比较方便，所以想参考一下。目前我想利用webpack搭建一个自动打包各个模块的开发环境，目前能够将js文件进行打包，但在mcss的编译和打包这个问题上遇到了一些困难。我看到rgui-tools的依赖里面使用了gulp和gulp_mcss，而regular的项目里面也好像用到了相关的工具。之前没有接触过webpack和gulp，所以我还慢慢摸索，不知道您是否能给我一些建议？谢谢！

**Comment by rainfore** [comment]
@elcarim5efil 你可以参考regular-ui v0.1的一些架构：https://github.com/regular-ui/regular-ui，webpack和gulp主要还是要自己学习文档摸索。我也是一步步过来的，加油！

**Comment by elcarim5efil** [comment]
嗯~现在已经搭好基本的环境了,目前正在考虑多页面的情况下怎么配置.谢谢您的建议和鼓励!
